apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: {{ .Values.configmap.db_host }}
  DB_PORT: {{ .Values.configmap.db_port }}
  DB_NAME: {{ .Values.configmap.db_name }}
