{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.configmap }}
  {{ $key | quote }}: {{ $value | quote }}
{{- end }}
{{- end }}
