apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: {{ .Values.configmap.db_host | quote }}
  DB_PORT: {{ .Values.configmap.db_port | quote }}
  DB_NAME: {{ .Values.configmap.db_name | quote }}
