name: mi-app-otsugua-3

namespace: otsugua04-dev

container:
  tag: 23
  port: 3000
  image: otsugua04/servicio-bdd
  replicas: 2
  cpuRequests: "500m"
  memRequests: "800Mi"
  cpuLimits: "1000m"
  memLimits: "1500Mi"

service:
  type: ClusterIP
  nodeport: 30967
  port: 3000
  targetPort: 3000

labels:
    app: mi-app-otsugua-3
 
hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

configmap:
  db_host: "postgres"
  db_port: "5432"
  db_name: "mi_basedatos"

secret:
  # plain text password; template will base64-encode when placing into `data:`
  password: "hola"
  db_username: "admin"
  db_password: "password"